name: Build and Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.3.0
      - name: Setup Java 21
        uses: actions/setup-java@v5.0.0
        with:
          java-version: '21'
          distribution: 'corretto'
      - name: Build with Maven
        run: mvn clean package -DskipTests
      - name: Copy JAR to EC2
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "target/hospital-management-*.jar"
          target: "/home/${{ secrets.EC2_USER }}/"
      - name: Deploy and Run JAR on EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Stopping existing server service..."
            pkill -f 'hospital-management-*.jar' || echo "No existing service to stop."
            echo "Starting new service..."
            cd /home/${{ secrets.EC2_USER }}/
            JAR_FILE=$(ls hospital-management-*.jar | head -n 1)
            
            if [ -z "$JAR_FILE" ]; then
              echo "No Jar file found to run."
              exit 1
            fi
            
            echo "RUNNING JAR FILE: $JAR_FILE"
            nohup java -jar "$JAR_FILE" --spring.profiles.active=prod > eva_hospital.log 2>&1 &
            
            echo "Service Started successfully"
            echo "You can check logs with 'tail -f eva_hospital.log'."